---
# Source: demoapp/charts/lambda/templates/lambda-event-source-mapping.yaml
# Source: demoapp/charts/lambda/templates/lambda.yaml
apiVersion: lambda.services.k8s.aws/v1alpha1
kind: EventSourceMapping
metadata:
  name: prod-lambda
  namespace: ack-lambda
  annotations:
    services.k8s.aws/region: us-east-2
spec:
  functionName: prod-lambda
  eventSourceARN: arn:aws:sqs:us-east-2:471112663315:prod-conversion-to-pdf--20240824145207513000000003.fifo
  batchSize: 10
